using FlowForge.Domain.Entities;
using FlowForge.Domain.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FlowForge.WebApi.Controllers;

/// <summary>
/// Allows FlowForge Agents (WorkflowHost instances) to self-register using
/// a registration token generated by an admin for a specific host group.
/// No JWT is required — the registration token itself serves as authentication.
/// </summary>
[ApiController]
[Route("api/hosts")]
[AllowAnonymous]
public class HostRegistrationController(
    IHostGroupRepository hostGroupRepo,
    IWorkflowHostRepository hostRepo,
    ILogger<HostRegistrationController> logger) : ControllerBase
{
    [HttpPost("register")]
    public async Task<IActionResult> Register([FromBody] RegisterHostRequest request, CancellationToken ct)
    {
        if (string.IsNullOrWhiteSpace(request.Token) || string.IsNullOrWhiteSpace(request.HostName))
            return BadRequest(new { Message = "Token and HostName are required." });

        // Find the host group that owns this token
        var groups = await hostGroupRepo.GetAllWithTokenAsync(ct);
        var group = groups.FirstOrDefault(g => g.ValidateRegistrationToken(request.Token));

        if (group is null)
        {
            logger.LogWarning("Agent registration failed: invalid token for host {HostName}", request.HostName);
            return Unauthorized(new { Message = "Invalid or expired registration token." });
        }

        // Upsert: if host already exists by name, update its group assignment
        var existing = await hostRepo.GetByNameAsync(request.HostName, ct);
        if (existing is not null)
        {
            logger.LogInformation("Agent {HostName} re-registered to group {GroupName}",
                request.HostName, group.Name);
            await hostRepo.SaveAsync(existing, ct);

            return Ok(new RegisterHostResponse(
                existing.Id, existing.Name, group.Id, group.Name, group.ConnectionId));
        }

        var host = WorkflowHost.Create(request.HostName, group.Id);
        await hostRepo.SaveAsync(host, ct);

        logger.LogInformation("Agent {HostName} registered to group {GroupName}", request.HostName, group.Name);

        return Created($"/api/host-groups/{group.Id}/hosts", new RegisterHostResponse(
            host.Id, host.Name, group.Id, group.Name, group.ConnectionId));
    }

    public record RegisterHostRequest(string Token, string HostName);
    public record RegisterHostResponse(Guid HostId, string HostName, Guid HostGroupId, string HostGroupName, string ConnectionId);
}
